[workspace]
members = ["kernel"]
exclude = [
  "stdlib",
  "programs/ping",
  "programs/dhcp",
  "programs/dns",
  "programs/ls",
  "programs/cat",
  "programs/ifconfig",
  "programs/arp",
  "programs/sysinfo",
  "programs/dmesg",
  "programs/system/init",
  "programs/system/terminal",
  "programs/system/taskmanager",
  "programs/system/settings",
  "programs/system/finder",
  "programs/system/notepad",
  "programs/system/imgview",
  "programs/system/videoplayer",
  "programs/system/diagnostics",
  "programs/system/calc",
  "programs/system/fontviewer",
  "programs/system/clock",
  "programs/system/screenshot",
  "programs/system/netmon",
  "programs/system/audiomon",
  "programs/system/compositor/dock",
  "programs/system/compositor/compositor",
  "programs/mkdir",
  "programs/rm",
  "programs/touch",
  "programs/cp",
  "programs/mv",
  "programs/date",
  "programs/sleep",
  "programs/hostname",
  "programs/ftp",
  "programs/wget",
  "programs/play",
  "programs/pipes",
  "programs/devlist",
  "programs/echo",
  "programs/ps",
  "programs/kill",
  "programs/free",
  "programs/uptime",
  "programs/uname",
  "programs/pwd",
  "programs/wc",
  "programs/hexdump",
  "programs/head",
  "programs/tail",
  "programs/clear",
  "programs/env",
  "programs/grep",
  "programs/find",
  "programs/sort",
  "programs/uniq",
  "programs/rev",
  "programs/stat",
  "programs/df",
  "programs/cal",
  "programs/seq",
  "programs/yes",
  "programs/true",
  "programs/false",
  "programs/whoami",
  "programs/which",
  "programs/strings",
  "programs/base64",
  "programs/xxd",
  "programs/set",
  "programs/export",
  "programs/dll/uisys",
  "programs/dll/uisys_client",
  "programs/dll/libimage",
  "programs/dll/libimage_client",
  "programs/dll/libfont",
  "programs/dll/libfont_client",
  "programs/dll/librender",
  "programs/dll/librender_client",
  "programs/dll/libcompositor",
  "programs/dll/libcompositor_client",
]
resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
