[package]
name = "dock"
version = "0.1.0"
edition = "2021"

[dependencies]
anyos_std = { path = "../../../../stdlib" }
libcompositor_client = { path = "../../../dll/libcompositor_client" }
libimage_client = { path = "../../../dll/libimage_client" }

[profile.dev]
panic = "abort"
opt-level = 2
