[package]
name = "anyos-uefi-boot"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi = { version = "0.36", features = ["alloc", "global_allocator"] }

[profile.release]
opt-level = "s"
lto = true

[workspace]
