[package]
name = "compositor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyos_std = { path = "../../../libs/stdlib" }
librender_client = { path = "../../../libs/librender_client" }
libimage_client = { path = "../../../libs/libimage_client" }

[profile.dev]
panic = "abort"
opt-level = 2
