[package]
name = "apkg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyos_std = { path = "../../libs/stdlib" }
libzip_client = { path = "../../libs/libzip_client" }
dynlink = { path = "../../libs/dynlink" }

[profile.dev]
panic = "abort"
opt-level = 2

[profile.release]
panic = "abort"
