[package]
name = "finder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyos_std = { path = "../../../stdlib" }
uisys_client = { path = "../../dll/uisys_client" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
