[package]
name = "jscript"
version = "0.1.0"
edition = "2021"

[dependencies]
anyos_std = { path = "../../libs/stdlib" }
libjs = { path = "../../libs/libjs" }

[profile.dev]
panic = "abort"
opt-level = 2

[profile.release]
panic = "abort"
